USE Shipping

GO

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN

SELECT * FROM TRIP
WHERE Trip_ID = 4 and Ship_ID = 1

UPDATE TRIP
SET Date_arrival = '20/05/2017 15:12:50'
WHERE  Trip_ID = 4 and Ship_ID = 1

UPDATE TRIP
SET Date_arrival = '22/05/2017 11:10:20'
WHERE Trip_ID = 1 and Ship_ID = 1

COMMIT






