USE Shipping

--SET TRANSACTION ISOLATION LEVEL READ COMMITTED
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION

UPDATE TRIP
SET Date_arrival = '20/05/2018 17:17:30'
WHERE Trip_ID = 4 and Ship_ID = 1

 
--возврат
UPDATE TRIP
SET Date_arrival = '25/12/2018 16:56:00'
WHERE Trip_ID = 4 and Ship_ID = 1

COMMIT

SELECT @@TRANCOUNT